#!/bin/bash

PROJECT_PATH="$1"
ENV_PATH="$PROJECT_PATH/env"
PROJECT_NAME=$(basename $PROJECT_PATH)

main () {
    main_command="source env/bin/activate && clear"
    if [[ -d "$ENV_PATH" ]]; then
        tmux send-keys -t $PROJECT_NAME "$main_command" C-m
        exit 0
    else
        tmux send-keys -t $PROJECT_NAME "python3 -m venv env && $main_command" C-m
        exit 0
    fi
}

main
